version: '3'

services:
  redis-master:
    image: redis:latest
    network_mode: host
    container_name: master
    command: redis-server /etc/redis/redis.conf
    volumes: 
      - ./storage:/data
      - ./config/redis:/etc/redis/


  sentinel-1:
    image: redis:latest
    network_mode: host
    container_name: sentinel1
    command: redis-sentinel /etc/redis/sentinel.conf 
    volumes:
      - ./config/sentinel/:/etc/redis/

