version: '3'

services:
  redis-slave2:
    image: redis:latest
    network_mode: host
    container_name: slave2
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /home/redis3/storage:/data/
      - ./config/redis/:/etc/redis/
  

  sentinel-3:
    image: redis:latest
    network_mode: host
    container_name: sentinel3
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./config/sentinel/:/etc/redis/
